### ISSUE TITLE
Deliver pre-compiled libmcljava.so

### ISSUE THREAD

**Issue by this-kramer** [cryptimeleon/mclwrap#25]
Currently, one has to manually install mcl. It would be easier to use, especially in a containerized context, if we could deliver a pre-compiled default version of mcl that is used if mcl is not installed.

**Comment by rheitjoh** [comment]
Good idea, I'll try and add some binaries.

**Comment by rheitjoh** [comment]
I added the precompiled .so file from my Linux on [this branch](https://github.com/cryptimeleon/mclwrap/tree/precompiled-lib) in the `lib` folder. I am not sure about compatiblity with other systems, especially other Linux distros. Maybe you could test it on yours, @this-kramer ?

**Comment by JanBobolz** [comment]
To clarify: the whole issue would ask to:

- Package .dll, .so files into the jar (by placing them in src/main/resources)
- Configure the lib loading code to fall back to using the dll/so [from the jar](https://stackoverflow.com/questions/1611357/how-to-make-a-jar-file-that-includes-dll-files) if the lib is not found on the system.

While we're at it, we might as well compile it for several platforms and package them all. Windows, Linux (x86, ARM), macOS (x86, M1). Ideally, we could get a script that does this automatically so that version bumps are easy to do.

**Comment by JanBobolz** [comment]
Also, quick note: please check mcl's license. If we want to ship the binary, we probably have to distribute their license alongside.

**Comment by this-kramer** [comment]
> I added the precompiled .so file from my Linux on [this branch](https://github.com/cryptimeleon/mclwrap/tree/precompiled-lib) in the `lib` folder. I am not sure about compatiblity with other systems, especially other Linux distros. Maybe you could test it on yours, @this-kramer ?

Works on my machine (Ubuntu 20.04)

**Comment by JanBobolz** [comment]
This is fixed by #33
